# Generated by Django 4.2.4 on 2023-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakshatra_lord_for_dasa_table',
            name='class_dasa',
        ),
        migrations.RemoveField(
            model_name='nakshatra_lord_for_dasa_table',
            name='lord_nakshtra',
        ),
        migrations.RemoveField(
            model_name='nakshatra_lord_for_dasa_table',
            name='type_dasa',
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='ascendant_from_extent',
            field=models.CharField(blank=True, max_length=30, verbose_name='ASCENDANT FROM EXTENT'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='ascendant_to_extent',
            field=models.CharField(blank=True, max_length=30, verbose_name='ASCENDANT TO EXTENT'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwadasottari_period_dasa',
            field=models.CharField(blank=True, db_column='DWADASOTTARI  PERIOD OF DASA ', max_length=30, verbose_name='DWADASOTTARI  PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwadasottari_planet',
            field=models.CharField(blank=True, db_column='DWADASOTTARI PLANET', max_length=30, verbose_name='DWADASOTTARI PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shodashottari_period_dasa',
            field=models.CharField(blank=True, db_column='SHODASHOTTARI  PERIOD OF DASA ', max_length=30, verbose_name='SHODASHOTTARI  PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shodashottari_planet',
            field=models.CharField(blank=True, db_column='SHODASHOTTARI  PLANET', max_length=30, verbose_name='SHODASHOTTARI  PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='type_paksha',
            field=models.CharField(blank=True, db_column='TYPE OF PAKSHA', max_length=30, verbose_name='TYPE OF PAKSHA'),
        ),
    ]
