# Generated by Django 4.2.4 on 2023-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_Api', '0002_remove_nakshatra_lord_for_dasa_table_class_dasa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shatyhayani_Dasa_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_extent', models.CharField(blank=True, db_column='Extent From (SS-DD-MM-SS)', max_length=30, verbose_name='Extent From (SS-DD-MM-SS)')),
                ('to_extent', models.CharField(blank=True, db_column='Extent To (SS-DD-MM-SS)', max_length=30, verbose_name='Extent To (SS-DD-MM-SS)')),
                ('Nakshatra_name', models.CharField(blank=True, db_column='Nakshatra Name', max_length=100)),
                ('shatyhayani_period_dasa', models.CharField(blank=True, db_column='shatyhayani PERIOD OF DASA ', max_length=30, verbose_name='shatyhayani PERIOD OF DASA')),
                ('shatyhayani_planet', models.CharField(blank=True, db_column='shatyhayani PLANET', max_length=30, verbose_name='shatyhayani PLANET')),
            ],
            options={
                'verbose_name': '101. Shatyhayani  Deity (Devta) for REMEDIES Table',
                'verbose_name_plural': '101. Shatyhayani  Deity (Devta) for REMEDIES Table',
            },
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='chatursitisama_period_dasa',
            field=models.CharField(blank=True, db_column='chatursitisama PERIOD OF DASA ', max_length=30, verbose_name='chatursitisama PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='chatursitisama_planet',
            field=models.CharField(blank=True, db_column='chatursitisama PLANET', max_length=30, verbose_name='chatursitisama PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwisaptatisama_period_dasa',
            field=models.CharField(blank=True, db_column='dwisaptatisama PERIOD OF DASA ', max_length=30, verbose_name='dwisaptatisama PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwisaptatisama_planet',
            field=models.CharField(blank=True, db_column='dwisaptatisama PLANET', max_length=30, verbose_name='dwisaptatisama PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='panchottari_period_dasa',
            field=models.CharField(blank=True, db_column='panchottari PERIOD OF DASA ', max_length=30, verbose_name='panchottari PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='panchottari_planet',
            field=models.CharField(blank=True, db_column='panchottari PLANET', max_length=30, verbose_name='panchottari PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='satabdika_period_dasa',
            field=models.CharField(blank=True, db_column='satabdika PERIOD OF DASA ', max_length=30, verbose_name='satabdika PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='satabdika_planet',
            field=models.CharField(blank=True, db_column='satabdika PLANET', max_length=30, verbose_name='satabdika PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shattrimsamsasama_from_extent',
            field=models.CharField(blank=True, max_length=30, verbose_name='shattrimsamsasama FROM EXTENT'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shattrimsamsasama_period_dasa',
            field=models.CharField(blank=True, db_column='shattrimsamsasama PERIOD OF DASA ', max_length=30, verbose_name='shattrimsamsasama PERIOD OF DASA'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shattrimsamsasama_planet',
            field=models.CharField(blank=True, db_column='shattrimsamsasama PLANET', max_length=30, verbose_name='shattrimsamsasama PLANET'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shattrimsamsasama_to_extent',
            field=models.CharField(blank=True, max_length=30, verbose_name='shattrimsamsasama TO EXTENT'),
        ),
        migrations.AddField(
            model_name='nakshatra_lord_for_dasa_table',
            name='type_birthtime',
            field=models.CharField(blank=True, db_column='TYPE OF birthtime', max_length=30, verbose_name='TYPE OF birthtime'),
        ),
        migrations.AlterField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwadasottari_period_dasa',
            field=models.CharField(blank=True, db_column='dwadasottari PERIOD OF DASA ', max_length=30, verbose_name='dwadasottari PERIOD OF DASA'),
        ),
        migrations.AlterField(
            model_name='nakshatra_lord_for_dasa_table',
            name='dwadasottari_planet',
            field=models.CharField(blank=True, db_column='dwadasottari PLANET', max_length=30, verbose_name='dwadasottari PLANET'),
        ),
        migrations.AlterField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shodashottari_period_dasa',
            field=models.CharField(blank=True, db_column='shodashottari PERIOD OF DASA ', max_length=30, verbose_name='shodashottari PERIOD OF DASA'),
        ),
        migrations.AlterField(
            model_name='nakshatra_lord_for_dasa_table',
            name='shodashottari_planet',
            field=models.CharField(blank=True, db_column='shodashottari PLANET', max_length=30, verbose_name='shodashottari PLANET'),
        ),
    ]
